export const wordsArray = [
  "Strawberry", "Eclipse", "Chandelier", "Ketchup", "Toothpaste", "Rainbow", "Bunk bed", "Boardgame", "Beehive", "Lemon",
  "Wreath", "Waffles", "Bubble", "Whistle", "Snowball", "Bouquet", "Headphones", "Fireworks", "Igloo", "Ferris wheel",
  "Banana peel", "Lawnmower", "Summer", "Whisk", "Cupcake", "Sleeping bag", "Bruise", "Fog", "Crust", "Battery Paris",
  "Beach", "Mountains", "Hawaii", "Mount Rushmore", "USA", "Hospital", "Attic", "Japan", "Library", "Desert",
  "Mars", "Washington DC", "Las Vegas", "Train station", "North Pole", "Farm", "Disney World", "Mexico", "Giraffe",
  "Koala", "Wasp", "Scorpion", "Lion", "Salamander", "Dolphin", "Frog", "Panda", "Platypus", "T-rex",
  "Meerkat", "Eagle", "Mailman", "Superman", "Justin Beiber", "Cowboy", "Alexander Hamilton", "Robin Hood", "Vampire",
  "Pirate", "Girl Scout", "Pikachu", "Spongebob", "Baby Yoda", "Pilgrim", "Cinderella", "Baker", "Abe Lincoln",
  "Thief", "Leprechaun", "Harry Potter", "Shrek", "Yoshi", "Queen Elizabeth", "Skip", "Burp", "Cook",
  "Scratch", "Sleep", "Plant", "Purchase", "Text", "Tie", "Snore", "Catch", "Study", "Olympics",
  "Sandcastle", "Recycle", "Black hole", "Applause", "Blizzard", "Sunburn", "Time machine", "Lace", "Monday",
  "Atlantis", "Swamp", "Panama Canal", "Sunscreen", "Dictionary", "Vanilla", "Century","pen", "caterpillar", "rocket", "alligator", "pizza", "shirt", "kite", "eyes", "chair", "cup", "jacket", "hippo", "bird",
  "monster", "bracelet", "coat", "balloon", "dinosaur", "head", "book", "mouse", "smile", "bridge", "blocks", "milk", "eye",
  "oval", "snowflake", "broom", "cheese", "lion", "lips", "beach", "cloud", "bus", "elephant", "sunglasses", "lemon", "star",
  "spoon", "boat", "turtle", "drum", "doll", "ant", "motorcycle", "bike", "pencil", "bunk bed", "moon", "inchworm", "slide",
  "hat", "cat", "tail", "helicopter", "square", "Mickey Mouse", "octopus", "door", "table", "egg", "bell", "nose", "spider",
  "horse", "finger", "glasses", "jar", "girl", "ear", "lizard", "flower", "snowman", "baby", "car", "bread", "blanket", "apple",
  "bench", "skateboard", "pig", "ice cream cone", "frog", "feet", "lollipop", "heart", "ears", "bed", "carrot", "person", "boy",
  "train", "truck", "bug", "legs", "bowl", "lamp", "desk", "purse", "light", "mountain", "snail", "basketball", "orange", "bear",
  "chicken", "grass", "cookie", "clock", "ghost", "spider web", "ocean", "monkey", "shoe", "dog", "face", "circle", "water",
  "butterfly", "house", "robot", "mouth", "branch", "worm", "socks", "grapes", "crab", "banana", "computer", "bee", "whale",
  "seashell", "snake", "sun", "swing", "bat", "pie", "wheel", "bunny", "hand", "cherry", "jellyfish", "tree", "stairs", "duck",
  "leaf", "dragon", "giraffe", "ball", "pants", "ring", "airplane", "candle", "cow", "cupcake", "football", "hamburger", "bone",
  "corn", "trip", "cobra", "bottle", "curtains", "soap", "mailman", "banana peel", "railroad", "back", "lipstick", "knee", "broccoli",
  "face", "tape", "hot dog", "shadow", "lawnmower", "table", "trash can", "rainbow", "hippopotamus", "soda", "laundry basket",
  "city", "match", "hill", "violin", "mailbox", "tire", "pumpkin", "zebra", "shelf", "eel", "beach", "salt and pepper", "ladder",
  "blue jeans", "address", "radish", "sea turtle", "dress", "lid", "family", "ladybug", "window", "cheeseburger", "yo-yo", "frog",
  "whistle", "glove", "magazine", "church", "chameleon", "boot", "tongue", "hospital", "thief", "smile", "potato", "hairbrush",
  "stork", "computer", "school", "heel", "pogo stick", "tent", "cucumber", "fox", "three-toed sloth", "sprinkler", "garden",
  "blowfish", "crib", "wing", "brain", "net", "song", "drums", "bagel", "baby", "starfish", "corner", "carpet", "bicycle",
  "strawberry", "horse", "rug", "puzzle", "snowball", "aircraft", "gate", "sidewalk", "pan", "marshmallow", "bell pepper",
  "watering can", "plate", "jungle", "camera", "forehead", "towel", "surfboard", "coin", "watch", "chin", "key", "blimp",
  "cowboy", "picture frame", "piano", "lake", "pirate", "box", "paw", "toast", "swimming pool", "silverware", "salt", "tissue",
  "shovel", "hoof", "dominoes", "roller blading", "base", "rose", "spider web", "hopscotch", "spoon", "elbow", "pinwheel",
  "french fries", "log", "doorknob", "bag", "attic", "beaver", "unicorn", "seahorse", "scar", "snowflake", "eraser", "jelly",
  "battery", "easel", "jar", "barn", "bathtub", "paperclip", "photograph", "maid", "ring", "outside", "vase", "electrical outlet",
  "room", "birthday cake", "map", "coconut", "spool", "chocolate chip cookie", "muffin", "ski", "stapler", "t-shirt", "lock",
  "braid", "seesaw", "half", "paper", "pizza", "dock", "shoulder", "lunchbox", "spring", "treasure", "queen", "fang", "round",
  "dragonfly", "newspaper", "mail", "knot", "tusk", "umbrella", "ticket", "lawn mower", "shark", "neck", "toothbrush", "hook",
  "wax", "mop", "beehive", "forest", "money", "napkin", "wreath", "music", "quilt", "chain", "backbone", "sheep", "banana split",
  "baseball", "basket", "printer", "cello", "circus", "whisk", "dimple", "hummingbird", "nest", "wrench", "fork", "garage",
  "stump", "pine tree", "saw", "stove", "toaster", "park", "hula hoop", "garbage", "peanut", "daddy longlegs", "hair", "bib",
  "spare", "light switch", "king", "headband", "America", "nature", "milk", "refrigerator", "mattress", "tennis", "popsicle",
  "stomach", "pajamas", "password", "nail", "stamp", "nut", "palace", "gingerbread man", "dog leash", "front porch", "wood",
  "mitten", "rhinoceros", "popcorn", "teeth", "stingray", "happy", "onion", "wall", "pen", "alarm clock", "door", "crayon",
  "swing", "maze", "jewelry", "golf", "gift", "bowtie", "fur", "gumball", "pear", "tiger", "peach", "washing machine", "doormat",
  "desk", "hockey", "crack", "cast", "flashlight", "dustpan", "scissors", "skate", "wallet", "sink", "coal", "brick", "hug",
  "doghouse", "deep", "pelican", "page", "lightsaber", "toe", "rake", "tulip", "torch", "teapot", "bucket", "trumpet", "paint",
  "hair dryer", "pineapple", "calendar", "pretzel", "candle", "sailboat", "storm", "tank", "volcano", "flute", "ironing board",
  "clam", "waist", "catfish", "top hat", "skirt", "astronaut", "rain", "button", "dollar", "spaceship", "fishing pole",
  "video camera", "penguin", "lemon", "poodle", "hip", "roof", "state", "claw", "clown", "rocking chair", "belt", "mini blinds",
  "airport", "cheetah", "spine", "pond", "cage", "mouse", "bomb", "ice", "cake", "cockroach", "batteries", "fist", "flamingo",
  "purse", "lighthouse", "manatee", "iPad", "telephone", "harp", "eagle", "electricity", "lobster", "cheek", "shallow",
  "suitcase", "campfire", "flagpole", "chalk", "artist", "skunk", "apple pie", "mushroom", "corndog", "smoke", "ship", "grill",
  "food", "cricket", "pencil", "TV", "rolly polly", "dolphin", "bathroom scale", "bubble", "porcupine", "owl", "stoplight",
  "chimney", "light bulb", "deer", "platypus"
];


export const getWordsArrayLength=()=>{
  return wordsArray.length
}
